"""
Типы для speech_recognition
"""

from typing import Any, Optional

class Recognizer:
    def adjust_for_ambient_noise(self, source: Any, duration: int = 1) -> None: ...
    def listen(self, source: Any, timeout: Optional[int] = None, 
               phrase_time_limit: Optional[int] = None) -> Any: ...
    def recognize_google(self, audio: Any, language: str = "en-US") -> str: ...

class Microphone:
    def __init__(self, device_index: Optional[int] = None, 
                 sample_rate: int = 16000, chunk_size: int = 1024) -> None: ...

class WaitTimeoutError(Exception): ...
class UnknownValueError(Exception): ...
class RequestError(Exception): ...
